# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- master

pool:  
   name: Default 

variables:
  phpVersion: 7.2

steps:
- script: |
    update-alternatives --set php /usr/bin/php$(phpVersion)
    update-alternatives --set phar /usr/bin/phar$(phpVersion)
    update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    D:\Instaladores\laragon\bin\php\php-7.4.10-Win32-vc15-x64\php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: php D:\Instaladores\laragon\bin\php\php-7.4.10-Win32-vc15-x64\phpunit-9.5.phar --version
  displayName: 'Run tests with phpunit'
